language: node_js

node_js:
- node

addons:
    code_climate:
        repo_token: 5e219fc4ec0ebb906e90eb7b4d7d09b930a02d06057eea46c559e5edefef243e

before_install:
  - npm install -g mocha
  - npm install -g nyc
  - npm install -g codeclimate-test-reporter

after_script:
  - nyc report --reporter text -- npm -s test
  - codeclimate < ./coverage/lcov.info
